spring:
  http:
    log-request-details: true

slack:
  baseUrl: https://slack.com/api/
  token: key_in_your_slack_key
  channel: webflux_demo
  proxyHost: ${PROXY_HOST:}
  proxyPort: ${PROXY_PORT:8080}

filewatcher:
  cacheSize: 5
  deviceDirectories:
      LIVING_ROOM : /home/wyc/ws/temp/living_room
      CARPORCH : /home/wyc/ws/temp/car_porch

logging:
  level:
    com.carrotlicious.iot.slackbot: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE